In [2]:
# import libraries

import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [3]:
df=pd.read_csv('ipl_data.csv')

In [4]:
df.head()

,match_id,team,opponent,venue,player_role,runs_scored,balls_faced,strike_rate,wickets,economy,age,match_result,commentary
0,1,PBKS,RCB,Chinnaswamy,NaN,38.0,20.0,52.71,1.0,8.98,28.0,Win,Spin bowlers turned the game around in the mid...
1,2,KKR,CSK,Chepauk,Wicket-Keeper,1.0,59.0,124.08,0.0,4.68,NaN,Win,Spin bowlers turned the game around in the mid...
2,3,RR,KKR,Wankhede,Wicket-Keeper,2.0,36.0,76.82,0.0,4.41,19.0,Tie,"The crowd was electric tonight, great atmosphere."
3,4,SRH,MI,Feroz Shah Kotla,Bowler,112.0,19.0,NaN,0.0,8.25,23.0,Win,Spin bowlers turned the game around in the mid...
4,5,PBKS,RR,Narendra Modi Stadium,Bowler,100.0,67.0,161.63,2.0,8.33,31.0,Tie,Amazing fielding efforts saved many runs today.

## Categorical - Data encoding 

Label Encoding - each unique category is replaced with a simple number like (0,1,2)

In [5]:
le=LabelEncoder()

In [ ]:
# fit() → learns categories

# transform() → converts categories into binary columns

In [6]:
df['team_encoded']=le.fit_transform(df['team'])

In [7]:
df[['team','team_encoded']].drop_duplicates()

    team  team_encoded
0   PBKS             6
1    KKR             3
2     RR             8
3    SRH             9
5    LSG             4
6    RCB             7
14    DC             1
16    MI             5
21   CSK             0
24    GT             2

## One - Hot Encoding

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
ohe=OneHotEncoder()

encoded=ohe.fit_transform(df[['team']])
print(ohe.get_feature_names_out())

['team_CSK' 'team_DC' 'team_GT' 'team_KKR' 'team_LSG' 'team_MI'
 'team_PBKS' 'team_RCB' 'team_RR' 'team_SRH']

In [10]:
## fit - learn from data
## transform - whatever is learning in the fit will be applied

In [11]:
ohe=OneHotEncoder(sparse_output=False)

encoded=ohe.fit_transform(df[['team']])

ohe_df=pd.DataFrame(encoded, columns=ohe.get_feature_names_out())

print(ohe_df)

    team_CSK  team_DC  team_GT  team_KKR  team_LSG  team_MI  team_PBKS  \
0        0.0      0.0      0.0       0.0       0.0      0.0        1.0
1        0.0      0.0      0.0       1.0       0.0      0.0        0.0
2        0.0      0.0      0.0       0.0       0.0      0.0        0.0
3        0.0      0.0      0.0       0.0       0.0      0.0        0.0
4        0.0      0.0      0.0       0.0       0.0      0.0        1.0
5        0.0      0.0      0.0       0.0       1.0      0.0        0.0
6        0.0      0.0      0.0       0.0       0.0      0.0        0.0
7        0.0      0.0      0.0       0.0       0.0      0.0        1.0
8        0.0      0.0      0.0       0.0       0.0      0.0        0.0
9        0.0      0.0      0.0       0.0       0.0      0.0        0.0
10       0.0      0.0      0.0       1.0       0.0      0.0        0.0
11       0.0      0.0      0.0       0.0       0.0      0.0        0.0
12       0.0      0.0      0.0       0.0       0.0      0.0        0.0
13       0.0      0.0      0.0       0.0       0.0      0.0        0.0
14       0.0      1.0      0.0       0.0       0.0      0.0        0.0
15       0.0      0.0      0.0       0.0       0.0      0.0        0.0
16       0.0      0.0      0.0       0.0       0.0      1.0        0.0
17       0.0      0.0      0.0       0.0       0.0      0.0        0.0
18       0.0      1.0      0.0       0.0       0.0      0.0        0.0
19       0.0      0.0      0.0       0.0       0.0      1.0        0.0
20       0.0      0.0      0.0       0.0       0.0      0.0        0.0
21       1.0      0.0      0.0       0.0       0.0      0.0        0.0
22       0.0      0.0      0.0       0.0       1.0      0.0        0.0
23       0.0      1.0      0.0       0.0       0.0      0.0        0.0
24       0.0      0.0      1.0       0.0       0.0      0.0        0.0
25       1.0      0.0      0.0       0.0       0.0      0.0        0.0
26       0.0      0.0      0.0       0.0       1.0      0.0        0.0
27       0.0      0.0      0.0       0.0       0.0      0.0        0.0
28       0.0      0.0      0.0       0.0       0.0      0.0        1.0
29       0.0      0.0      0.0       1.0       0.0      0.0        0.0
30       0.0      0.0      1.0       0.0       0.0      0.0        0.0
31       0.0      0.0      0.0       0.0       0.0      0.0        0.0
32       0.0      0.0      0.0       0.0       0.0      0.0        0.0
33       0.0      0.0      0.0       0.0       0.0      0.0        0.0
34       0.0      0.0      0.0       0.0       0.0      0.0        1.0
35       0.0      0.0      0.0       0.0       0.0      0.0        0.0
36       0.0      0.0      1.0       0.0       0.0      0.0        0.0
37       0.0      0.0      0.0       0.0       0.0      0.0        1.0
38       0.0      0.0      0.0       0.0       0.0      1.0        0.0
39       0.0      0.0      0.0       1.0       0.0      0.0        0.0
40       0.0      0.0      1.0       0.0       0.0      0.0        0.0
41       0.0      0.0      0.0       0.0       0.0      1.0        0.0
42       0.0      0.0      0.0       0.0       1.0      0.0        0.0
43       0.0      0.0      1.0       0.0       0.0      0.0        0.0
44       0.0      0.0      0.0       0.0       1.0      0.0        0.0
45       0.0      0.0      0.0       0.0       0.0      0.0        0.0
46       0.0      0.0      0.0       0.0       0.0      1.0        0.0
47       0.0      0.0      0.0       1.0       0.0      0.0        0.0
48       0.0      0.0      0.0       0.0       0.0      0.0        1.0
49       0.0      0.0      0.0       0.0       0.0      0.0        0.0

    team_RCB  team_RR  team_SRH
0        0.0      0.0       0.0
1        0.0      0.0       0.0
2        0.0      1.0       0.0
3        0.0      0.0       1.0
4        0.0      0.0       0.0
5        0.0      0.0       0.0
6        1.0      0.0       0.0
7        0.0      0.0       0.0
8        0.0      1.0       0.0
9        0.0      0.0       1.0
10       0.0      0.0       0.0
11       0.0      1.0       0.0
12       0.0      1.0       0.0
13       1.0      0.0       0.0
14       0.0      0.0       0.0
15       0.0      0.0       1.0
16       0.0      0.0       0.0
17       0.0      1.0       0.0
18       0.0      0.0       0.0
19       0.0      0.0       0.0
20       0.0      0.0       1.0
21       0.0      0.0       0.0
22       0.0      0.0       0.0
23       0.0      0.0       0.0
24       0.0      0.0       0.0
25       0.0      0.0       0.0
26       0.0      0.0       0.0
27       1.0      0.0       0.0
28       0.0      0.0       0.0
29       0.0      0.0       0.0
30       0.0      0.0       0.0
31       1.0      0.0       0.0
32       0.0      0.0       1.0
33       1.0      0.0       0.0
34       0.0      0.0       0.0
35       0.0      0.0       1.0
36       0.0      0.0       0.0
37       0.0      0.0       0.0
38       0.0      0.0       0.0
39       0.0      0.0       0.0
40       0.0      0.0       0.0
41       0.0      0.0       0.0
42       0.0      0.0       0.0
43       0.0      0.0       0.0
44       0.0      0.0       0.0
45       0.0      0.0       1.0
46       0.0      0.0       0.0
47       0.0      0.0       0.0
48       0.0      0.0       0.0
49       0.0      1.0       0.0

In [14]:
ohe=OneHotEncoder(sparse_output=False)

encoded=ohe.fit_transform(df[['team']])

ohe_df=pd.DataFrame(encoded, columns=ohe.get_feature_names_out())

res=pd.concat([df,ohe_df],axis=1)

#res = pd.concat([df['team'],ohe_df],axis=1)
print(res.head(10))

   match_id  team opponent                  venue    player_role  runs_scored  \
0         1  PBKS      RCB            Chinnaswamy            NaN         38.0
1         2   KKR      CSK                Chepauk  Wicket-Keeper          1.0
2         3    RR      KKR               Wankhede  Wicket-Keeper          2.0
3         4   SRH       MI       Feroz Shah Kotla         Bowler        112.0
4         5  PBKS       RR  Narendra Modi Stadium         Bowler        100.0
5         6   LSG      KKR           Eden Gardens    All-Rounder        112.0
6         7   RCB       MI            Chinnaswamy  Wicket-Keeper         55.0
7         8  PBKS       DC       Feroz Shah Kotla         Bowler         80.0
8         9    RR       DC           Eden Gardens    All-Rounder         58.0
9        10   SRH      LSG           Eden Gardens  Wicket-Keeper        112.0

   balls_faced  strike_rate  wickets  economy  ...  team_CSK team_DC team_GT  \
0         20.0        52.71      1.0     8.98  ...       0.0     0.0     0.0
1         59.0       124.08      0.0     4.68  ...       0.0     0.0     0.0
2         36.0        76.82      0.0     4.41  ...       0.0     0.0     0.0
3         19.0          NaN      0.0     8.25  ...       0.0     0.0     0.0
4         67.0       161.63      2.0     8.33  ...       0.0     0.0     0.0
5         19.0       158.14      5.0     9.10  ...       0.0     0.0     0.0
6         20.0        96.21      4.0     9.81  ...       0.0     0.0     0.0
7         71.0       131.38      1.0    11.81  ...       0.0     0.0     0.0
8         52.0       126.32      1.0     8.13  ...       0.0     0.0     0.0
9         33.0       145.45      2.0     6.58  ...       0.0     0.0     0.0

   team_KKR  team_LSG  team_MI  team_PBKS  team_RCB  team_RR  team_SRH
0       0.0       0.0      0.0        1.0       0.0      0.0       0.0
1       1.0       0.0      0.0        0.0       0.0      0.0       0.0
2       0.0       0.0      0.0        0.0       0.0      1.0       0.0
3       0.0       0.0      0.0        0.0       0.0      0.0       1.0
4       0.0       0.0      0.0        1.0       0.0      0.0       0.0
5       0.0       1.0      0.0        0.0       0.0      0.0       0.0
6       0.0       0.0      0.0        0.0       1.0      0.0       0.0
7       0.0       0.0      0.0        1.0       0.0      0.0       0.0
8       0.0       0.0      0.0        0.0       0.0      1.0       0.0
9       0.0       0.0      0.0        0.0       0.0      0.0       1.0

[10 rows x 24 columns]

## Ordinal Encoding

In [23]:
from sklearn.preprocessing import OrdinalEncoder 

order = [['Loss','Tie','Win']]

oe = OrdinalEncoder(categories=order)

df['outcome_encoded']=oe.fit_transform(df[['match_result']])

print(df[['match_result','outcome_encoded']].drop_duplicates())

  match_result  outcome_encoded
0          Win              2.0
2          Tie              1.0
5         Loss              0.0